name: Vale Lint

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.j2'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.j2'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Vale
      run: |
        curl -sSfL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh
        sudo mv vale /usr/local/bin/

    - name: Run Vale
      run: |
        vale --output=JSON . | jq .
