name: Vale Lint

on:
  push:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.j2'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.j2'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Vale
      run: |
        curl -sSfL https://github.com/errata-ai/vale/releases/download/v2.17.0/vale_2.17.0_Linux_64-bit.tar.gz -o vale.tar.gz
        tar -xzf vale.tar.gz
        sudo mv vale /usr/local/bin/
        rm vale.tar.gz

    - name: Run Vale
      run: |
        vale --output=JSON . | jq .
